FROM golang:alpine as builder
COPY src/ /go/src
WORKDIR /go/src
RUN go build -o /go/bin/printbox .

FROM moltencan/docker-compose2
COPY --from=builder /go/bin/printbox /usr/local/bin/printbox
COPY ep.sh /ep.sh

ENTRYPOINT [ "/ep.sh" ]
